networks:
  public-dev:
    external: true
    name: public-univ-dev
services:
  traefik2:
    image: traefik:2.11
    networks:
      - public-univ-dev
    container_name: docker_univ_traefik
    restart: unless-stopped
    profiles: ['runner']
    security_opt:
      - no-new-privileges:true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-univ=true
      - traefik.http.routers.traefik-univ.tls=true
      - traefik.http.routers.traefik-univ.rule=Host(`traefik.docker.localhost`)
      - traefik.http.services.traefik-univ.loadbalancer.server.port=8080
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik-data/configurations/dynamic.yml:/etc/traefik/dynamic_conf.yaml:ro
      - ./traefik-data/traefik.yml:/etc/traefik/traefik.yaml:ro
      - ./traefik-data/certs:/etc/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  portainer:
    image: portainer/portainer-ce:alpine-sts
    container_name: docker_univ_portainer
    restart: unless-stopped
    networks:
      - public-univ-dev
    profiles: ['runner']
    security_opt:
      - no-new-privileges:true
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer-univ=true
      - traefik.http.routers.portainer-univ.entrypoints=websecure
      - traefik.http.routers.portainer-univ.rule=Host(`portainer.docker.localhost`)
      - traefik.http.routers.portainer-univ.tls=true
      - traefik.http.routers.portainer-univ.service=portainer-univ
      - traefik.http.middlewares.portainer-univ.redirectscheme.scheme=https
      - traefik.http.middlewares.portainer-univ.redirectscheme.permanent=true
      - traefik.http.services.portainer-univ.loadbalancer.server.port=9000
      - traefik.http.services.portainer-univ.loadbalancer.server.scheme=http
  php:
    container_name: container_${PROJECT}_${DOCKER_ENV}
    image: my_socle_univ_${PROJECT}_${DOCKER_ENV}
    user: ${CURRENT_UID:-1000}
    profiles: ['runner']
    networks:
      - public-univ-dev
    build:
      context: ./my-project/${PROJECT}
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./my-project/${PROJECT}:/var/www/html/${PROJECT}:rw
      - ./tools:/opt/tools
    env_file: "./my-project/${PROJECT}/socle.env"
    labels:
      - traefik.http.routers.php-niji.rule=Host(`${URL_LOCAL_WEBSITE}`)
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-debug}"
      XDEBUG_CONFIG: "client_host=$IP_WSL_ETH"
      PHP_IDE_CONFIG: "serverName=${URL_LOCAL_WEBSITE}"
  mysql:
    container_name: container_mysql
    image: mysql:9
    profiles: ['runner']
    networks:
      - public-univ-dev
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-nopassword}
      - MYSQL_DATABASE=mybdd
      - MYSQL_USER=user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nopassword}
    volumes:
      - mysql-data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
  pma:
    container_name: container_pma
    image: phpmyadmin:5.1.0-apache
    profiles: ['runner']
    environment:
      PMA_HOST: app_mysql
      PMA_USER: root
      PMA_PASSWORD: nopassword
      UPLOAD_LIMIT: 1G
      PHP_MAX_INPUT_VARS: 1G
      PMA_ARBITRARY: 1
      PMA_ABSOLUTE_URI: 'https://pma.docker.localhost'
    volumes:
        - ./tools/docker/pma/config.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
      - "8080:80"
    networks:
      - public-univ-dev
    depends_on:
      - app_mysql
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin-univ.rule=Host(`pma.docker.localhost`)
      - traefik.http.routers.phpmyadmin-univ.tls=true