networks:
  public-univ-dev:
    external: true
    name: public-univ-dev
volumes:
  portainer_data:
  mysql-data:
services:
  app_traefik:
    extends:
      file: ../../common-services.yml
      service: traefik2
  app_portainer:
    extends:
      file: ../../common-services.yml
      service: portainer
  app_mysql:
    extends:
      file: ../../common-services.yml
      service: mysql
  app_pma:
    extends:
      file: ../../common-services.yml
      service: pma
  app_php:
    extends:
      file: ../../common-services.yml
      service: php